apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd-tutorial
    app.kubernetes.io/instance: argocd-tutorial
  name: argocd-tutorial
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-tutorial
  template:
    metadata:
      labels:
        app: argocd-tutorial
    spec:
      containers:
        - image: 'ghcr.io/misw-4301-desarrollo-apps-en-la-nube/argocd-tutorial:6.0'
          imagePullPolicy: Always
          name: argocd-tutorial
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
