kind: Service
apiVersion: v1
metadata:
  name: argocd-tutorial
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: argocd-tutorial
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080